// AUTO-GENERATED by .design-sync/prep-sources.mjs — do not edit by hand.
import React from 'react';
import { MemoryRouter } from 'react-router-dom';

// ── Web components (allop-web/src, real source in place; default exports) ──
export { default as Nav } from '../../src/components/Nav';
export { default as Footer } from '../../src/components/Footer';
export { default as SalonCard } from '../../src/components/SalonCard';
export { default as CookieBanner } from '../../src/components/CookieBanner';
export { default as ToastProvider } from '../../src/components/ToastProvider';

// ── Dashboard components (copied into staging; named exports) ──
export { Button, Badge, Icon, Avatar, Field, Switch } from './dashboard/components/primitives';
export { Rail } from './dashboard/components/Rail';
export { ContextBar } from './dashboard/components/ContextBar';

// ── Preview-only provider: nests every context the previews read. Contexts are
//    independent, so wrapping dashboard components in the web providers is
//    harmless. Not a card (absent from componentSrcMap). ──
import { ThemeProvider } from '../../src/lib/theme';
import { I18nProvider } from '../../src/lib/i18n';
import ToastProviderInner from '../../src/components/ToastProvider';
export function DSPreviewProvider({ children }) {
  return React.createElement(
    MemoryRouter,
    null,
    React.createElement(
      ThemeProvider,
      null,
      React.createElement(
        I18nProvider,
        null,
        React.createElement(ToastProviderInner, null, children),
      ),
    ),
  );
}
